### User register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName": "Swami",
    "lastName": "Sriharsha",
    "email": "sriharsha@gmail.com",
    "password": "Swami",
    "profileImageUrl": "xyz.png"
}

### Author register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName": "Shobu",
    "lastName": "Sai ram",
    "email": "shobu@gmail.com",
    "password": "Shobu",
    "profileImageUrl": "abc.png"
}

### Common authentication/login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "newPassword"
}


### Create article
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author": "69896ec86319f1673e6f783f",
    "title": "sample title 2",
    "content": "sample content 2",
    "category": "sample category 2"
}

### Read author's articles
GET http://localhost:4000/author-api/articles/69896ec86319f1673e6f783f

### Update/edit author's article
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author": "69896ec86319f1673e6f783f",
    "title": "sample title 1 updated",
    "content": "sample content 1",
    "category": "sample category 1 updated",
    "articleId": "69898feb5ba023b28dff1290"
}

### soft delete an article
PUT http://localhost:4000/author-api/articles/delete
Content-Type: application/json

{
    "author": "69896ec86319f1673e6f783f",
    "articleId": "69897ebdcec6cc29b7809c91"
}

### Read all articles
GET http://localhost:4000/user-api/articles/698969abb485d9709a091434

### Add a comment
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "userId": "698969abb485d9709a091434",
    "articleId": "69897ebdcec6cc29b7809c91",
    "comment": "The article was awesome!"
}

### Logout
GET  http://localhost:4000/common-api/logout

### Test req
GET http://localhost:4000/hello


### admin blocks user
PUT http://localhost:4000/admin-api/block
Content-Type: application/json

{
    "userEmail": "shobu@gmail.com"
}

### admin unblocks user
PUT http://localhost:4000/admin-api/unblock
Content-Type: application/json

{
    "userEmail": "sriharsha@gmail.com"
}

###Change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "currentPassword": "password",
    "newPassword": "newPassword"
}